host: site-app-5479.database.com
client_id: '3MVG99qusVZJwhsn3LOiCA1PR_.86yfW8x1PhldhFk4kkaMH6yU12REdagEhKlzxJzAjTBBKp7hmWpQBRUPrP'
client_secret: '3902132454851307367'
username: anaserdb@dimensions.ps
password: 'sterio200304HYTnVBVlTMQYfdqka3pqfI'
debugging: true